### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Beanv587** [MicrosoftDocs/windows-driver-docs#3812]
### Type of issue

Other (describe below)

### Feedback

Hello, I want to register for the Hardware Developer Program. Follow the steps on this page (https://learn.microsoft.com/zh-cn/windows-hardware/drivers/dashboard/get-started-dashboard-submissions?source=recommendations #step-2-register-for-the-hardware-developer-program),Open this link https://go.microsoft.com/fwlink/?LinkID=828002. The redirected page is not the page to register for the Hardware Developer Program...

In fact, 1 month ago this page should have redirected to https://partner.microsoft.com/en-us/dashboard/Registration/Tenant/CreateTenant

But I don’t know why even if I manually open this page https://partner.microsoft.com/en-us/dashboard/Registration/Tenant/CreateTenant, I cannot complete the registration. After I fill in the information, the page will exit and let me Login again.. I cannot proceed to the Certificate step...

I don't know what happened, but I hope it can be fixed soon.Thank you

### Page URL

https://go.microsoft.com/fwlink/?LinkID=828002

### Content source URL

https://learn.microsoft.com/zh-cn/windows-hardware/drivers/dashboard/get-started-dashboard-submissions?source=recommendations#step-2-register-for-the-hardware-developer-program

### Author

anaharris-ms

**Comment by jianghui3132749** [comment]
i have the same question. i want to regiest Hardware Developer, but i can not.

**Comment by anaharris-ms** [comment]
Hi @Beanv587, thank you so much bringing this to our attention. I've fixed the link, and things should be working now. Let me know if you need anything else.

#please-close

**Comment by Beanv587** [comment]
> Hi @Beanv587, thank you so much bringing this to our attention. I've fixed the link, and things should be working now. Let me know if you need anything else.
> 
> #please-close

I still can't register for the Hardware Developer Program. When I visit https://go.microsoft.com/fwlink/?LinkID=828002, it prompts me to register a Microsoft account. After I register the account, it asks me to join a program. But there is no Hardware Developer Program I want...

![1](https://github.com/MicrosoftDocs/windows-driver-docs/assets/30143806/b3ff8edf-6417-41df-9ce8-daa45c3de8fd)

![2](https://github.com/MicrosoftDocs/windows-driver-docs/assets/30143806/64e20696-f941-43b8-9c95-120be2fe90c3)

**Comment by Beanv587** [comment]
If I sigin using my work account, the page looks like this:

![3](https://github.com/MicrosoftDocs/windows-driver-docs/assets/30143806/59e823f6-5c5c-4130-aed5-e5264f68e8d5)

Still no hardware developer program

**Comment by Beanv587** [comment]
@anaharris-ms

**Comment by jianghui3132749** [comment]
yes，i have the same question.  Still no hardware developer program

**Comment by Beanv587** [comment]
> yes，i have the same question. Still no hardware developer program

Hope they fix it soon

**Comment by anaharris-ms** [comment]
Hi @jianghui3132749 and @Beanv587, I am looking into this for you. It's late here, but I will be hopefully resolving this issue for your tomorrow! I deeply apologize for any inconvenience.

**Comment by Beanv587** [comment]
> Hi @jianghui3132749 and @Beanv587, I am looking into this for you. It's late here, but I will be hopefully resolving this issue for your tomorrow! I deeply apologize for any inconvenience.

Thank you

**Comment by anaharris-ms** [comment]
Hi, I have spoken to the internal team here. For this issue, you'll need to contact support at https://review.learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support?branch=pr-en-us-2301#technical-support-issues.

I am so sorry for any inconvenience.

**Comment by jjwwiodyne** [comment]
@anaharris-ms When I try to click on Developer Support I get "The request is blocked.
0Km/nZQAAAAAZc/72KMslTZyJLhSF99wdQ082QUEzMTUwODA3MDE3ADg1MjU3MDQwLWY4YzUtNDFkZS05MTdiLWM1NzJiZGM5MDBiYg=="

**Comment by anaharris-ms** [comment]
@jjwwiodyne, 

Try this: https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support?branch=main

**Comment by jjwwiodyne** [comment]
Thanks @anaharris-ms for your assistance. I'm still seeing it
blocked...here's a screencast: https://share.zight.com/NQuBpQl9

Is there a support email or phone number we can call? This is getting
really frustrating sorting this out on our own.

**Comment by anaharris-ms** [comment]
@jjwwiodyne,

I will look into this as well. Hope to get back to you later this evening. Thanks for your patience!

**Comment by jjwwiodyne** [comment]
@anaharris-ms Thank you! We're eager to get our drivers signed.

**Comment by anaharris-ms** [comment]
@jjwwiodyne, Can you check to see if there are any ad blockers or something else on your end. I am having no problems accessing the site, and support is not having any access issues.

**Comment by jjwwiodyne** [comment]
@anaharris-ms It appears that the site only works with Microsoft Edge not
Chrome or Safari on Mac. I was able to submit a ticket now. Thank you.

**Comment by anaharris-ms** [comment]
@jjwwiodyne,

I'm glad you got that resolved. I will let them know that it doesn't work on Chrome or Safari on Mac.

**Comment by jianghui3132749** [comment]
@jjwwiodyne  The response from the support team to me

Hi Team,
 
We are aware that the hardware registration page is currently unavailable. We apologize for any inconvenience this may have caused. Our team is actively working to remediate the issue and restore the page as soon as possible. However, at this time we do not have an estimated time of resolution.
 
I will proceed to close the ticket.
 
Kindest Regards,
Juan
Your Partners at Microsoft
Office Hours 8AM – 5PM US CT
v-juangue@microsoft.com
[Contact Support](https://developer.microsoft.com/en-us/windows/support/?tabs=keytopics)

**Comment by jianghui3132749** [comment]
this is a photo

![support](https://github.com/MicrosoftDocs/windows-driver-docs/assets/39110030/49dc6723-fdb7-4404-b30b-2ace3ddc9554)

**Comment by Beanv587** [comment]
> Hi, I have spoken to the internal team here. For this issue, you'll need to contact support at https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support?branch=main
> 
> I am so sorry for any inconvenience.

OK,Thanks

**Comment by Beanv587** [comment]
> Hi, I have spoken to the internal team here. For this issue, you'll need to contact support at https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support?branch=main
> 
> I am so sorry for any inconvenience.

@anaharris-ms OK,Thanks

**Comment by Beanv587** [comment]
> jianghui3132749

@jianghui3132749 looks like we have to wait for a while...

**Comment by jjwwiodyne** [comment]
@anaharris-ms Any word when we can enroll into the hardware program? The support case I opened 9 days ago just told me to wait. We seriously need to get our drivers signed or this is going to cost us customers Is there a phone number we can escalate this at? Feel free to PM me.

**Comment by Beanv587** [comment]
> @anaharris-ms Any word when we can enroll into the hardware program? The support case I opened 9 days ago just told me to wait. We seriously need to get our drivers signed or this is going to cost us customers Is there a phone number we can escalate this at? Feel free to PM me.

I'm in the same situation as you. The team is waiting for my driver signature. . .
